# Generated by Django 4.1.3 on 2022-11-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_create_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'buses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='busmodel',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_number',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
