# Generated by Django 4.1.3 on 2022-11-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_schedule_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['-departure_date', 'price']},
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_date',
            field=models.DateField(default='2022-02-02'),
            preserve_default=False,
        ),
    ]
